export enum Genre {
  Comedy = 'Comedy',
  Fantasy = 'Fantasy',
  Crime = 'Crime',
  Drama = 'Drama',
  Music = 'Music',
  Adventure = 'Adventure',
  History = 'History',
  Thriller = 'Thriller',
  Animation = 'Animation',
  Family = 'Family',
  Mystery = 'Mystery',
  Biography = 'Biography',
  Action = 'Action',
  FilmNoir = 'Film-Noir',
  Romance = 'Romance',
  SciFi = 'Sci-Fi',
  War = 'War',
  Western = 'Western',
  Horror = 'Horror',
  Musical = 'Musical',
  Sport = 'Sport'
}
